### GET request to clamd-api server 使用API key认证
GET http://localhost:8080/ping
Content-Type: application/json
X-API-Key: Esd0LKwbQnD2YgAgLfv53SOYc7gKIia3txshjJpH-Ds=

### POST request to clamd-api server 使用API key认证
GET http://localhost:8080/version
Content-Type: application/json
X-API-Key: Esd0LKwbQnD2YgAgLfv53SOYc7gKIia3txshjJpH-Ds=

### POST request to clamd-api server 使用API key认证
GET http://localhost:8080/reload
Content-Type: application/json
X-API-Key: Esd0LKwbQnD2YgAgLfv53SOYc7gKIia3txshjJpH-Ds=


### POST request to clamd-api server 使用API key认证
POST http://localhost:8080/scan
Content-Type: application/json
X-API-Key: Esd0LKwbQnD2YgAgLfv53SOYc7gKIia3txshjJpH-Ds=

{
    "file": "/Users/nrgao/GolandProjects/clamd-api/clamd-api.http"
}
